New About Us Product Text
ScilifelabDataCentre/precision-medicine-portal-frontend pull request #49
Opened 2024-05-24 12:20 UTC by JanProgrammierung

Updated the product text based on Natashia's md file in NextCloud.
New p element instead of markdown components for now.

2024-05-25 16:27 UTC, SevLG requested changes
I mentioned it in the other PR as well, but could we collect all/most of the main content like this in the content.ts file? Or what do you think? I think it would be more consistent to have it all in one place, but it's not super necessary.

2024-05-27 14:40 UTC, JanProgrammierung commented
I agree that it would be the best case. I am wondering though how this would work with links and linebreaks (paragraphs). We could use react-markdown library but we haven't added that yet. Otherwise it could be it's own component but it would not match the layout of the previous / other content.ts texts.
What do you think?

2024-05-27 17:29 UTC, SevLG commented
> I agree that it would be the best case. I am wondering though how this would work with links and linebreaks (paragraphs). We could use react-markdown library but we haven't added that yet. Otherwise it could be it's own component but it would not match the layout of the previous / other content.ts texts. What do you think? @SevLG

Linebreaks could be done by adding '\n' in the string, but you're right that links would be a bit more difficult, it would need to be a JSX object probably. We can keep it as it is for now and look at a solution for that later.

2024-05-27 17:29 UTC, SevLG approved these changes

2024-05-28 08:12 UTC, merged