Developed clinical registry page
ScilifelabDataCentre/precision-medicine-portal-frontend pull request #55
Opened 2024-08-15 11:16 UTC by natashiab

I've done most of the page now - there are still some descriptions missing for a bunch of the registries, and some of the URLs lead to the wrong place / have a broken link. But this is because some of them don't have any proper web page. So we have to decide if to keep those without a website or not as they wouldn't be clickable? 

I have to go through all of the JSON file and see which these are, but I think it's **a separate task.** 

I also changed the size of the "main" white header on all pages as I thought this one looked huge in comparison to the rest of the page(s). Let me know what you think.

2024-08-15 13:32 UTC, JanProgrammierung requested changes
Great!
Even simplified and improved some parts of the original DataSourcesComponent

Comments:
1.
The interface ( name needs to be changed to have an I in front of it. This is a common naming convention to identify something as an interface :)
RegistrySources -> IRegistrySources
RegistrySourcesFilters -> IRegistrySourcesFilters

2.
bg-[#E9F2D1] is a Tailwind class, however, the color is hardcoded. We use softcoded colors which you can find in the tailwind.config.js file. So it would f.ex. like bg-primary. It would be best if you could find one of the colors from there and apply it. (Secret hint: if any color doesn't fit at all, you can still pick it and change the opacity via Tailwind CSS)

3.
I realized in the json file that some of the search tags start lowercased and some uppercased. Could be good to have this consistent.

4. The green box that is currently in the left column is a bit distracting. Should we maybe put this to the top of the page similar as the "info" boxes on KIARVA? You can copy paste the code from there and just change the color and text.

Otherwise the page looks great in itself. It is responsive now and looks okay on a mobile phone. I will recommend Sebbe to include the same design in the DataSources page.

It might be necessary to do some minor changes later once the page is filled and the JSON fully integrated.

2024-09-18 17:48 UTC, SevLG commented
Fixed the errors I found but would be good to double check, I had some issues when trying to update the branch the first time so I'm worried something got broken. Looks OK to me when I test it though.

2024-09-18 18:11 UTC, SevLG commented
Did a hacky "hotix" of the vulnerability warnings, not sure if they actually helped but I'm not sure if it's something we need to worry about either.

2024-09-19 09:50 UTC, JanProgrammierung approved these changes

2024-09-19 09:50 UTC, merged